# Site settings
title: Rainloury'S BLOG
description: Liu Yu
favicon: /assets/img/favicon.ico
baseurl:
url: https://rainloury.github.io
rss_url:

# Build settings

highlight: true
#highlighter: rouge

timezone: Asia/Shanghai

markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  
syntax_highlighter_opts: true
